# -*- coding: utf-8 -*-
"""Dataset de mots pour Griffonne ! — 5 langues, 4 niveaux.

  "1" = ★     très facile
  "2" = ★★    simple
  "3" = ★★★   moyen/dur
  "4" = ★★★★  quasi impossible (abstrait)

Chaque mot ajouté est validé contre les lexiques dicts/<lang>.txt.
"""

WORDS = {

"fr": {
"1": [
"chat","chien","maison","soleil","lune","étoile","arbre","fleur","voiture",
"vélo","avion","bateau","train","fusée","montagne","plage","pizza",
"croissant","baguette","fromage","gâteau","glace","pomme","banane","fraise",
"carotte","champignon","poisson","requin","baleine","papillon","araignée",
"serpent","éléphant","girafe","lion","pingouin","tortue","lapin","souris",
"dragon","fantôme","pirate","robot","sorcière","licorne","sirène","chevalier",
"château","couronne","guitare","piano","tambour","trompette","microphone",
"télévision","téléphone","ordinateur","horloge","parapluie","lunettes",
"chapeau","chaussure","chaussette","pantalon","écharpe","ballon",
"cerf-volant","toboggan","balançoire","piscine","douche","brosse à dents",
"savon","miroir","fenêtre","porte","escalier","échelle","pont","phare",
"moulin","igloo","tente","feu de camp","arc-en-ciel","nuage","éclair","neige",
"bonhomme de neige","cadeau","anniversaire","clown","cirque","magicien",
"vampire","squelette","zombie","momie","extraterrestre","main","pied","nez",
"bouche","oreille","bras","jambe","doigt","tête","langue","banc","table",
"chaise","bol","assiette","fourchette","couteau","cuillère","verre",
"casserole","lait","jus","café","thé","miel","glaçon","bonbon","chocolat",
"biscuit","bus","taxi","roue","clou","vis","scie","hache","corde","boîte",
"sac","bonnet","gant","botte","robe","jupe","manteau","pyjama","ours","loup",
"renard","tigre","zèbre","canard","poussin","nœud","bébé","roi","reine",
"prince","princesse","ange","pluie","mer","lac","rivière","école","jardin",
"herbe","feuille","orange","poire","pêche","kiwi","melon","citrouille",
"tomate","pain","beurre","confiture","crêpe","soupe","riz","œil","genou",
"coude","coq","chèvre","âne","fourmi","mouche","coccinelle","cygne","pigeon",
"aigle","hippopotame","rhinocéros","gorille","chameau","cerf","sanglier",
],
"2": [
"astronaute","planète","volcan","île","trésor","clé","cadenas","bougie",
"livre","crayon","ciseaux","marteau","tournevis","aimant","boussole","carte",
"drapeau","trophée","médaille","dinosaure","kangourou","hibou","abeille",
"escargot","grenouille","hérisson","spaghetti","hamburger","sandwich","œuf",
"poule","vache","mouton","cochon","cheval","singe","panda","koala",
"crocodile","flamant rose","pieuvre","crabe","méduse","hippocampe","dauphin",
"ancre","voilier","sous-marin","hélicoptère","montgolfière","tracteur",
"camion de pompier","ambulance","moto","skateboard","trottinette","luge",
"ski","patin à glace","raquette","football","basket","tennis","bowling",
"fléchettes","échecs","dé","puzzle","toupie","marionnette","nid","plume",
"aile","griffe","empreinte","os","cerveau","cœur","dent","moustache","barbe",
"chignon","tresse","couette","oreiller","lit","canapé","tabouret","lampe",
"cheminée","aspirateur","balai","seau","arrosoir","brouette","pelle","râteau",
"cactus","palmier","tournesol","cerise","citron","pastèque","ananas","raisin",
"maïs","brocoli","oignon","piment","sucette","donut","cupcake","pop-corn",
"frites","hot-dog","taco","sushi","théière","tasse","paille","bouteille",
"tonneau","panier","valise","sac à dos","portefeuille","pièce de monnaie",
"tirelire","diamant","bague","loupe","jumelles","télescope","appareil photo",
"pellicule","enveloppe","timbre","journal","calendrier","tableau","pinceau",
"palette","statue","fontaine","tour Eiffel","pyramide","sphinx","totem",
"grotte","cascade","désert","forêt","marais","banquise","comète","satellite",
"ovni","météorite","galaxie","sablier","grille-pain","micro-ondes",
"réfrigérateur","lave-linge","bouilloire","mixeur","poubelle","cintre",
"étagère","tiroir","rideau","tapis","coussin","vase","cadre photo",
"interrupteur","prise électrique","ampoule","pile","batterie","clavier",
"souris d'ordinateur","écran","casque audio","écouteurs","console de jeux",
"manette","drone","imprimante","clé USB","gomme","règle","compas","trombone",
"agrafeuse","punaise","cartable","trousse","feutre","craie","tableau noir",
"globe terrestre","microscope","éprouvette","stéthoscope","seringue",
"pansement","béquille","fauteuil roulant","thermomètre","ceinture","cravate",
"nœud papillon","bretelles","gilet","kimono","tablier","salopette","tongs",
"talons hauts","perroquet","paon","autruche","chauve-souris","taupe","castor",
"écureuil","raton laveur","blaireau","furet","homard","huître","moule",
"sardine","truite","anguille","raie","espadon","piranha","poisson-clown",
"policier","voleur","médecin","infirmière","pilote","soldat","viking","géant",
"ogre","elfe","troll","aiguille","fil","bouton","fermeture éclair","balance",
"ventilateur","radiateur","sonnette","boîte aux lettres","clôture",
"paillasson","brique","grue","pelleteuse","bouée","maillot de bain",
"serviette","parasol","cerceau","kayak","locomotive","wagon","tramway",
"métro","jungle","colline","falaise","dune","champ","grange","potager","zoo",
"musée","bibliothèque","hôpital","prison","banque","supermarché",
"boulangerie","restaurant","stade","gare","aéroport","port","usine","église",
"immeuble","gratte-ciel","orage","navette spatiale","astéroïde","éolienne",
"tondeuse","perceuse","lave-vaisselle","sèche-cheveux","fer à repasser",
"framboise","myrtille","abricot","prune","mangue","noix de coco","aubergine",
"courgette","concombre","poireau","radis","chou","chou-fleur","petits pois",
"haricot","épinards","gaufre","tarte","omelette","saucisse","jambon",
"moutarde","ketchup","mayonnaise","limonade","yaourt","macaron","ninja",
],
"3": [
"gargouille","vitrail","labyrinthe","échiquier","dominos","xylophone",
"accordéon","harpe","violon","saxophone","scaphandre","parachute",
"tyrolienne","funambule","trampoline","périscope","zeppelin","téléphérique",
"phoque","caméléon","paresseux","ornithorynque","tatou","narval","axolotl",
"mante religieuse","scarabée","luciole","corbeau","catapulte","armure",
"bouclier","arbalète","lanterne","chandelier","harpon","hamac","cabane",
"aquarium","épouvantail","déménagement","embouteillage","somnambule",
"apiculteur","ramoneur","ventriloque","contorsionniste","dompteur",
"archéologue","chef d'orchestre","château de sable","bataille de polochons",
"course d'escargots","montagnes russes","marché aux puces","chasse au trésor",
"feu d'artifice","éclipse solaire","aurore boréale","marée basse",
"sables mouvants","avalanche","tremblement de terre","tornade","canicule",
"brouillard","rosée","stalactite","geyser","empreintes digitales",
"code secret","passage secret","chambre forte","fouilles archéologiques",
"momification","hibernation","migration","camouflage","mue","pique-nique",
"barbecue","fondue","œuf à la coque","pièce montée","gueule de bois",
"torticolis","crampe","chair de poule","sieste","éternuement","plongeon",
"jonglage","escalade","équitation","escrime","tir à l'arc",
"plongée sous-marine","surf","canoë","parapente","garagiste","plombier",
"électricien","facteur","jardinier","boulanger","coiffeur","dentiste",
"vétérinaire","pompier","jongleur","acrobate","mime","chef cuisinier",
"serveur","arbitre","détective","espion","cow-boy","gladiateur","déguisement",
"carnaval","défilé","concert","karaoké","mariage","cache-cache",
"colin-maillard","chaise musicale","corde à sauter","marelle","billes",
"toboggan aquatique","paintball","tir à la corde","bras de fer",
"saut à l'élastique","marathon","saut en hauteur","saut à la perche",
"lancer de javelot","gymnastique","water-polo","curling","ping-pong",
"badminton","pétanque","pleine lune","étoile filante","constellation",
"voie lactée","trou noir","orbite","alunissage","décollage","atterrissage",
"naufrage","grande roue","moulin à eau","agriculteur","chirurgien","juge",
"avocat","capitaine","bûcheron","forgeron","berger","mineur","cascadeur",
"sculpteur","photographe","alpinisme","randonnée",
"bataille de boules de neige","pont-levis","donjon","château fort",
"échafaudage","tronçonneuse","longue-vue","girouette","paratonnerre",
"gouvernail","hublot","radeau","hutte","oasis","savane","canyon","cratère",
"épave","otarie","morse","lynx","guépard","panthère","hyène","gazelle",
"bison","élan","colibri","toucan","pélican","héron","cigogne","iguane",
"cobra","scorpion","grêle","verglas","inondation","ouragan","marteau-piqueur",
"tipi",
],
"4": [
"nostalgie","jalousie","insomnie","vertige","hoquet","frisson","télépathie",
"hypnose","amnésie","déjà-vu","claustrophobie","procrastination",
"métamorphose","photosynthèse","apesanteur","gravité","écho","silence",
"chaos","infini","liberté","démocratie","philosophie","conscience",
"intuition","sarcasme","ironie","malentendu","rumeur","superstition",
"cauchemar","solitude","courage","patience","espoir","destin","hasard",
"équilibre","vitesse","temps","électricité","wifi","allergie","karma",
"paradoxe","mirage","évolution","harmonie","curiosité","timidité",
"mélancolie","euphorie","adrénaline","empathie","charisme","aura","dilemme",
"utopie","anarchie","propagande","censure","inflation","chômage","burn-out",
"routine","monotonie","spontanéité","modestie","orgueil","trahison","pardon",
"suspense","instinct","ego","ambiance","gratitude","fierté","honte",
"culpabilité","regret","doute","confiance","méfiance","angoisse","sérénité",
"chance","malchance","coïncidence","illusion","imagination","créativité",
"inspiration","motivation","fatigue","ennui","stress","panique","phobie",
"obsession","nervosité","humour","politesse","respect","justice","injustice",
"égalité","fraternité","tolérance","sagesse","folie","rêverie","soupir",
"frimeur","malaise","vengeance","mémoire","rêve","vérité","mensonge","secret",
"promesse","blague","devinette","énigme","mystère","victoire","défaite",
"générosité","gentillesse","paresse","gourmandise","colère","joie",
"tristesse","peur","amour","amitié","enfance","jeunesse","vieillesse",
"éternité","crépuscule","aube","urgence","retard","grève","pollution",
"bonheur","malheur","surprise","appétit","faim","soif","fièvre","migraine",
"vacances",
],
},

"en": {
"1": [
"cat","dog","house","sun","moon","star","tree","flower","car","bicycle",
"airplane","boat","train","rocket","mountain","beach","pizza","pancake",
"bread","cheese","cake","ice cream","apple","banana","strawberry","carrot",
"mushroom","fish","shark","whale","butterfly","spider","snake","elephant",
"giraffe","lion","penguin","turtle","rabbit","mouse","dragon","ghost",
"pirate","robot","witch","unicorn","mermaid","knight","castle","crown",
"guitar","piano","drum","trumpet","microphone","television","telephone",
"computer","clock","umbrella","glasses","hat","shoe","sock","pants","scarf",
"balloon","kite","slide","swing","swimming pool","shower","toothbrush","soap",
"mirror","window","door","stairs","ladder","bridge","lighthouse","windmill",
"igloo","tent","campfire","rainbow","cloud","lightning","snow","snowman",
"gift","birthday","clown","circus","magician","vampire","skeleton","zombie",
"mummy","alien","hand","foot","nose","mouth","ear","arm","leg","finger",
"head","tongue","bench","table","chair","bowl","plate","fork","knife","spoon",
"glass","pan","milk","juice","coffee","tea","honey","ice cube","candy",
"chocolate","cookie","bus","taxi","wheel","nail","screw","saw","axe","rope",
"box","bag","beanie","glove","boot","dress","skirt","coat","pajamas","bear",
"wolf","fox","tiger","zebra","duck","chick","knot","baby","king","queen",
"prince","princess","angel","rain","sea","lake","river","school","garden",
"grass","leaf","orange","pear","peach","kiwi","melon","pumpkin","tomato",
"butter","jam","soup","rice","eye","knee","elbow","rooster","goat","donkey",
"ant","ladybug","swan","pigeon","eagle","hippopotamus","rhinoceros","gorilla",
"camel","deer","boar",
],
"2": [
"astronaut","planet","volcano","island","treasure","key","padlock","candle",
"book","pencil","scissors","hammer","screwdriver","magnet","compass","map",
"flag","trophy","medal","dinosaur","kangaroo","owl","bee","snail","frog",
"hedgehog","spaghetti","hamburger","sandwich","egg","chicken","cow","sheep",
"pig","horse","monkey","panda","koala","crocodile","flamingo","octopus",
"crab","jellyfish","seahorse","dolphin","anchor","sailboat","submarine",
"helicopter","hot air balloon","tractor","fire truck","ambulance",
"motorcycle","skateboard","scooter","sled","ski","ice skate","tennis racket",
"soccer","basketball","tennis","bowling","darts","chess","dice","puzzle",
"spinning top","puppet","nest","feather","wing","claw","footprint","bone",
"brain","heart","tooth","mustache","beard","ponytail","braid","blanket",
"pillow","bed","couch","stool","lamp","fireplace","vacuum cleaner","broom",
"bucket","watering can","wheelbarrow","shovel","rake","cactus","palm tree",
"sunflower","cherry","lemon","watermelon","pineapple","grapes","corn",
"broccoli","onion","chili pepper","lollipop","donut","cupcake","popcorn",
"french fries","hot dog","taco","sushi","teapot","cup","straw","bottle",
"barrel","basket","suitcase","backpack","wallet","coin","piggy bank",
"diamond","ring","magnifying glass","binoculars","telescope","camera",
"envelope","stamp","newspaper","calendar","painting","paintbrush","statue",
"fountain","pyramid","sphinx","totem pole","cave","waterfall","desert",
"forest","swamp","iceberg","comet","satellite","UFO","meteor","galaxy",
"hourglass","toaster","microwave","refrigerator","washing machine","kettle",
"blender","trash can","hanger","shelf","drawer","curtain","carpet","cushion",
"vase","photo frame","light switch","power outlet","light bulb","battery",
"keyboard","computer mouse","monitor","headphones","earbuds","game console",
"controller","drone","printer","USB stick","eraser","ruler","paperclip",
"stapler","pushpin","school bag","pencil case","marker","chalk","blackboard",
"globe","microscope","test tube","stethoscope","syringe","band-aid","crutch",
"wheelchair","thermometer","belt","tie","bow tie","suspenders","vest",
"kimono","apron","overalls","flip-flops","high heels","parrot","peacock",
"ostrich","bat","mole","beaver","squirrel","raccoon","badger","ferret",
"lobster","oyster","mussel","sardine","trout","eel","stingray","swordfish",
"piranha","clownfish","policeman","thief","doctor","nurse","pilot","soldier",
"ninja","viking","giant","ogre","elf","troll","needle","thread","button",
"zipper","fan","radiator","doorbell","mailbox","fence","doormat","brick",
"crane","excavator","buoy","swimsuit","towel","parasol","hoop","kayak",
"locomotive","wagon","tram","subway","jungle","hill","cliff","dune","field",
"barn","zoo","museum","library","hospital","prison","bank","supermarket",
"bakery","restaurant","stadium","airport","harbor","factory","church",
"skyscraper","thunderstorm","space shuttle","asteroid","wind turbine",
"lawn mower","drill","dishwasher","hair dryer","raspberry","blueberry",
"apricot","plum","mango","coconut","eggplant","zucchini","cucumber","leek",
"radish","cabbage","cauliflower","peas","bean","spinach","waffle","pie",
"omelet","sausage","ham","mustard","ketchup","mayonnaise","lemonade","yogurt",
],
"3": [
"gargoyle","stained glass","maze","chessboard","dominoes","xylophone",
"accordion","harp","violin","saxophone","diving suit","parachute","zipline",
"tightrope walker","trampoline","periscope","zeppelin","cable car","seal",
"chameleon","sloth","platypus","armadillo","narwhal","axolotl",
"praying mantis","beetle","firefly","raven","catapult","armor","shield",
"crossbow","lantern","chandelier","harpoon","hammock","treehouse","aquarium",
"scarecrow","moving day","traffic jam","sleepwalker","beekeeper",
"chimney sweep","ventriloquist","contortionist","lion tamer","archaeologist",
"orchestra conductor","sandcastle","pillow fight","snail race",
"roller coaster","flea market","treasure hunt","fireworks","solar eclipse",
"northern lights","low tide","quicksand","avalanche","earthquake","tornado",
"heatwave","fog","dew","stalactite","geyser","fingerprints","secret code",
"secret passage","bank vault","excavation","mummification","hibernation",
"migration","camouflage","shedding skin","picnic","barbecue","fondue",
"soft-boiled egg","wedding cake","hangover","stiff neck","cramp","goosebumps",
"nap","sneeze","diving","juggling","climbing","horse riding","fencing",
"archery","scuba diving","surfing","canoe","paragliding","mechanic","plumber",
"electrician","mailman","gardener","baker","hairdresser","dentist",
"veterinarian","firefighter","juggler","acrobat","mime","chef","waiter",
"referee","detective","spy","cowboy","gladiator","costume","carnival",
"parade","concert","karaoke","wedding","hide and seek","blind man's buff",
"musical chairs","jump rope","hopscotch","marbles","water park","paintball",
"tug of war","arm wrestling","bungee jumping","marathon","high jump",
"pole vault","javelin throw","gymnastics","water polo","curling","ping pong",
"badminton","petanque","full moon","shooting star","constellation",
"milky way","black hole","orbit","moon landing","liftoff","landing",
"shipwreck","ferris wheel","water mill","farmer","surgeon","judge","lawyer",
"captain","lumberjack","blacksmith","shepherd","miner","stuntman","sculptor",
"photographer","mountaineer","hiking","snowball fight","drawbridge","dungeon",
"fortress","jackhammer","scaffolding","chainsaw","spyglass","weather vane",
"lightning rod","rudder","porthole","raft","tepee","hut","oasis","savanna",
"canyon","crater","sea lion","walrus","lynx","cheetah","panther","hyena",
"gazelle","bison","moose","hummingbird","toucan","pelican","heron","stork",
"iguana","cobra","scorpion","hail","flood","hurricane",
],
"4": [
"nostalgia","jealousy","insomnia","dizziness","hiccups","shiver","telepathy",
"hypnosis","amnesia","déjà vu","claustrophobia","procrastination",
"metamorphosis","photosynthesis","zero gravity","gravity","echo","silence",
"chaos","infinity","freedom","democracy","philosophy","consciousness",
"intuition","sarcasm","irony","misunderstanding","rumor","superstition",
"nightmare","loneliness","courage","patience","hope","destiny","luck",
"balance","speed","time","electricity","wifi","allergy","karma","paradox",
"mirage","evolution","harmony","curiosity","shyness","melancholy","euphoria",
"adrenaline","empathy","charisma","aura","dilemma","utopia","anarchy",
"propaganda","censorship","inflation","unemployment","burnout","routine",
"monotony","spontaneity","modesty","pride","betrayal","forgiveness",
"suspense","instinct","ego","vibe","gratitude","shame","guilt","regret",
"doubt","trust","distrust","anxiety","serenity","bad luck","coincidence",
"illusion","imagination","creativity","inspiration","motivation","fatigue",
"boredom","stress","panic","phobia","obsession","nervousness","humor",
"politeness","respect","justice","injustice","equality","brotherhood",
"tolerance","wisdom","madness","daydream","sigh","show-off","awkwardness",
"revenge","gossip","peer pressure","memory","dream","truth","lie","secret",
"promise","joke","riddle","mystery","victory","defeat","generosity",
"kindness","laziness","gluttony","anger","joy","sadness","fear","love",
"friendship","childhood","youth","old age","eternity","dusk","dawn",
"emergency","delay","strike","pollution","happiness","sorrow","surprise",
"appetite","hunger","thirst","fever","migraine","vacation",
],
},

"es": {
"1": [
"gato","perro","casa","sol","luna","estrella","árbol","flor","coche",
"bicicleta","avión","barco","tren","cohete","montaña","playa","pizza",
"tortilla","pan","queso","pastel","helado","manzana","plátano","fresa",
"zanahoria","seta","pez","tiburón","ballena","mariposa","araña","serpiente",
"elefante","jirafa","león","pingüino","tortuga","conejo","ratón","dragón",
"fantasma","pirata","robot","bruja","unicornio","sirena","caballero",
"castillo","corona","guitarra","piano","tambor","trompeta","micrófono",
"televisión","teléfono","ordenador","reloj","paraguas","gafas","sombrero",
"zapato","calcetín","pantalón","bufanda","globo","cometa","tobogán",
"columpio","piscina","ducha","cepillo de dientes","jabón","espejo","ventana",
"puerta","escalera","puente","faro","molino","iglú","tienda de campaña",
"hoguera","arcoíris","nube","rayo","nieve","muñeco de nieve","regalo",
"cumpleaños","payaso","circo","mago","vampiro","esqueleto","zombi","momia",
"extraterrestre","astronauta","mano","pie","nariz","boca","oreja","brazo",
"pierna","dedo","cabeza","lengua","banco","mesa","silla","cuenco","plato",
"tenedor","cuchillo","cuchara","vaso","sartén","leche","zumo","café","té",
"miel","cubito de hielo","caramelo","chocolate","galleta","autobús","taxi",
"rueda","clavo","tornillo","sierra","hacha","cuerda","caja","bolsa","gorro",
"guante","bota","vestido","falda","abrigo","pijama","oso","lobo","zorro",
"tigre","cebra","pato","pollito","nudo","bebé","rey","reina","príncipe",
"princesa","ángel","lluvia","mar","lago","río","escuela","jardín","hierba",
"hoja","naranja","pera","melocotón","melón","calabaza","tomate","mantequilla",
"mermelada","sopa","arroz","ojo","rodilla","codo","gallo","cabra","burro",
"hormiga","mosca","mariquita","cisne","paloma","águila","hipopótamo",
"rinoceronte","gorila","camello","ciervo","jabalí","kiwi",
],
"2": [
"planeta","volcán","isla","tesoro","llave","candado","vela","libro","lápiz",
"tijeras","martillo","destornillador","imán","brújula","mapa","bandera",
"trofeo","medalla","dinosaurio","canguro","búho","abeja","caracol","rana",
"erizo","espagueti","hamburguesa","bocadillo","huevo","gallina","vaca",
"oveja","cerdo","caballo","mono","panda","koala","cocodrilo","flamenco",
"pulpo","cangrejo","medusa","caballito de mar","delfín","ancla","velero",
"submarino","helicóptero","globo aerostático","tractor","camión de bomberos",
"ambulancia","motocicleta","monopatín","patinete","trineo","esquí","fútbol",
"baloncesto","tenis","bolos","dardos","ajedrez","dado","rompecabezas",
"peonza","marioneta","nido","pluma","ala","garra","huella","hueso","cerebro",
"corazón","diente","bigote","barba","trenza","manta","almohada","cama","sofá",
"taburete","lámpara","chimenea","aspiradora","escoba","cubo","regadera",
"carretilla","pala","rastrillo","cactus","palmera","girasol","cereza","limón",
"sandía","piña","uvas","maíz","brócoli","cebolla","chile","piruleta",
"rosquilla","palomitas","patatas fritas","perrito caliente","taco","sushi",
"tetera","taza","pajita","botella","barril","cesta","maleta","mochila",
"cartera","moneda","hucha","diamante","anillo","lupa","prismáticos",
"telescopio","cámara","sobre","sello","periódico","calendario","cuadro",
"pincel","estatua","fuente","pirámide","esfinge","cueva","cascada","desierto",
"bosque","pantano","iceberg","cometa espacial","satélite","ovni","galaxia",
"reloj de arena","tostadora","microondas","nevera","lavadora","hervidor",
"batidora","papelera","percha","estantería","cajón","cortina","alfombra",
"cojín","jarrón","marco de fotos","interruptor","enchufe","bombilla","pila",
"teclado","ratón de ordenador","pantalla","auriculares","consola","mando",
"dron","impresora","memoria USB","goma de borrar","regla","clip","grapadora",
"chincheta","estuche","rotulador","tiza","pizarra","globo terráqueo",
"microscopio","tubo de ensayo","estetoscopio","jeringuilla","tirita","muleta",
"silla de ruedas","termómetro","cinturón","corbata","pajarita","tirantes",
"chaleco","kimono","delantal","peto","chanclas","tacones","loro","pavo real",
"avestruz","murciélago","topo","castor","ardilla","mapache","tejón","hurón",
"langosta","ostra","mejillón","sardina","trucha","anguila","raya",
"pez espada","piraña","pez payaso","policía","ladrón","médico","enfermera",
"piloto","soldado","gigante","ogro","elfo","trol","aguja","hilo","botón",
"cremallera","báscula","ventilador","radiador","timbre","buzón","valla",
"felpudo","ladrillo","grúa","excavadora","casco","boya","bañador","toalla",
"sombrilla","aro","locomotora","vagón","tranvía","metro","selva","colina",
"acantilado","duna","campo","granero","huerto","zoológico","museo",
"biblioteca","hospital","cárcel","supermercado","panadería","restaurante",
"estadio","estación","aeropuerto","puerto","fábrica","iglesia","rascacielos",
"tormenta","transbordador espacial","asteroide","cortacésped","taladro",
"lavavajillas","secador","plancha","frambuesa","arándano","albaricoque",
"ciruela","mango","coco","berenjena","calabacín","pepino","puerro","rábano",
"col","coliflor","guisantes","judía","espinacas","gofre","tarta","salchicha",
"jamón","mostaza","mayonesa","limonada","yogur","ninja","vikingo","kayak",
],
"3": [
"gárgola","vidriera","laberinto","tablero de ajedrez","dominó","xilófono",
"acordeón","arpa","violín","saxofón","escafandra","paracaídas","tirolina",
"equilibrista","cama elástica","periscopio","zepelín","teleférico","foca",
"camaleón","perezoso","ornitorrinco","armadillo","narval","ajolote",
"mantis religiosa","escarabajo","luciérnaga","cuervo","catapulta","armadura",
"escudo","ballesta","farol","candelabro","arpón","hamaca","cabaña","acuario",
"espantapájaros","mudanza","atasco","sonámbulo","apicultor","deshollinador",
"ventrílocuo","contorsionista","domador","arqueólogo","director de orquesta",
"castillo de arena","guerra de almohadas","carrera de caracoles",
"montaña rusa","mercadillo","búsqueda del tesoro","fuegos artificiales",
"eclipse solar","aurora boreal","marea baja","arenas movedizas","avalancha",
"terremoto","tornado","ola de calor","niebla","rocío","estalactita","géiser",
"huellas dactilares","código secreto","pasadizo secreto","caja fuerte",
"excavación","momificación","hibernación","migración","camuflaje",
"muda de piel","picnic","barbacoa","fondue","huevo pasado por agua",
"tarta de boda","resaca","tortícolis","calambre","piel de gallina","siesta",
"estornudo","salto de trampolín","malabares","escalada","equitación",
"esgrima","tiro con arco","buceo","surf","canoa","parapente","mecánico",
"fontanero","electricista","cartero","jardinero","panadero","peluquero",
"dentista","veterinario","bombero","malabarista","acróbata","mimo","cocinero",
"camarero","árbitro","detective","espía","vaquero","gladiador","disfraz",
"carnaval","desfile","concierto","karaoke","boda","escondite",
"gallinita ciega","sillas musicales","comba","rayuela","canicas",
"parque acuático","paintball","tiro de cuerda","pulso","puenting","maratón",
"salto de altura","salto con pértiga","lanzamiento de jabalina","gimnasia",
"waterpolo","curling","ping pong","bádminton","petanca","luna llena",
"estrella fugaz","constelación","vía láctea","agujero negro","órbita",
"alunizaje","despegue","aterrizaje","naufragio","noria","molino de agua",
"agricultor","cirujano","juez","abogado","capitán","leñador","herrero",
"pastor","minero","escultor","fotógrafo","alpinismo","senderismo",
"guerra de bolas de nieve","puente levadizo","mazmorra","fortaleza",
"martillo neumático","andamio","motosierra","catalejo","veleta","pararrayos",
"timón","ojo de buey","balsa","choza","oasis","sabana","cañón","cráter",
"león marino","morsa","lince","guepardo","pantera","hiena","gacela","bisonte",
"alce","colibrí","tucán","pelícano","garza","cigüeña","iguana","cobra",
"escorpión","granizo","inundación","huracán",
],
"4": [
"nostalgia","celos","insomnio","vértigo","hipo","escalofrío","telepatía",
"hipnosis","amnesia","déjà vu","claustrofobia","procrastinación",
"metamorfosis","fotosíntesis","ingravidez","gravedad","eco","silencio","caos",
"infinito","libertad","democracia","filosofía","conciencia","intuición",
"sarcasmo","ironía","malentendido","rumor","superstición","pesadilla",
"soledad","valentía","paciencia","esperanza","destino","suerte","equilibrio",
"velocidad","tiempo","electricidad","wifi","alergia","karma","paradoja",
"espejismo","evolución","armonía","curiosidad","timidez","melancolía",
"euforia","adrenalina","empatía","carisma","aura","dilema","utopía",
"anarquía","propaganda","censura","inflación","desempleo","agotamiento",
"rutina","monotonía","espontaneidad","modestia","orgullo","traición","perdón",
"suspenso","instinto","ego","ambiente","gratitud","vergüenza","culpa",
"arrepentimiento","duda","confianza","desconfianza","angustia","serenidad",
"mala suerte","coincidencia","ilusión","imaginación","creatividad",
"inspiración","motivación","fatiga","aburrimiento","estrés","pánico","fobia",
"obsesión","nerviosismo","humor","cortesía","respeto","justicia","injusticia",
"igualdad","fraternidad","tolerancia","sabiduría","locura","ensueño",
"suspiro","presumido","incomodidad","venganza","cotilleo","madrugón",
"memoria","sueño","verdad","mentira","secreto","promesa","broma","adivinanza",
"enigma","misterio","victoria","derrota","generosidad","amabilidad","pereza",
"gula","ira","alegría","tristeza","miedo","amor","amistad","infancia",
"juventud","vejez","eternidad","atardecer","amanecer","emergencia","retraso",
"huelga","contaminación","felicidad","sorpresa","apetito","hambre","sed",
"fiebre","migraña","vacaciones",
],
},

"de": {
"1": [
"Katze","Hund","Haus","Sonne","Mond","Stern","Baum","Blume","Auto","Fahrrad",
"Flugzeug","Boot","Zug","Rakete","Berg","Strand","Pizza","Brezel","Brot",
"Käse","Kuchen","Eis","Apfel","Banane","Erdbeere","Karotte","Pilz","Fisch",
"Hai","Wal","Schmetterling","Spinne","Schlange","Elefant","Giraffe","Löwe",
"Pinguin","Schildkröte","Hase","Maus","Drache","Gespenst","Pirat","Roboter",
"Hexe","Einhorn","Meerjungfrau","Ritter","Schloss","Krone","Gitarre",
"Klavier","Trommel","Trompete","Mikrofon","Fernseher","Telefon","Computer",
"Uhr","Regenschirm","Brille","Hut","Schuh","Socke","Hose","Schal",
"Luftballon","Drachen","Rutsche","Schaukel","Schwimmbad","Dusche",
"Zahnbürste","Seife","Spiegel","Fenster","Tür","Treppe","Leiter","Brücke",
"Leuchtturm","Windmühle","Iglu","Zelt","Lagerfeuer","Regenbogen","Wolke",
"Blitz","Schnee","Schneemann","Geschenk","Geburtstag","Clown","Zirkus",
"Zauberer","Vampir","Skelett","Zombie","Mumie","Außerirdischer","Hand","Fuß",
"Nase","Mund","Ohr","Arm","Bein","Finger","Kopf","Zunge","Bank","Tisch",
"Stuhl","Schüssel","Teller","Gabel","Messer","Löffel","Glas","Pfanne","Milch",
"Saft","Kaffee","Tee","Honig","Eiswürfel","Bonbon","Schokolade","Keks","Bus",
"Taxi","Rad","Nagel","Schraube","Säge","Axt","Seil","Kiste","Tasche","Mütze",
"Handschuh","Stiefel","Kleid","Rock","Mantel","Schlafanzug","Bär","Wolf",
"Fuchs","Tiger","Zebra","Ente","Küken","Knoten","Baby","König","Königin",
"Prinz","Prinzessin","Engel","Regen","Meer","See","Fluss","Schule","Garten",
"Gras","Blatt","Orange","Birne","Pfirsich","Kiwi","Melone","Kürbis","Tomate",
"Butter","Marmelade","Suppe","Reis","Auge","Knie","Ellbogen","Hahn","Ziege",
"Esel","Ameise","Mücke","Marienkäfer","Schwan","Taube","Adler","Nilpferd",
"Nashorn","Gorilla","Kamel","Hirsch","Wildschwein",
],
"2": [
"Astronaut","Planet","Vulkan","Insel","Schatz","Schlüssel","Vorhängeschloss",
"Kerze","Buch","Bleistift","Schere","Hammer","Schraubenzieher","Magnet",
"Kompass","Landkarte","Flagge","Pokal","Medaille","Dinosaurier","Känguru",
"Eule","Biene","Schnecke","Frosch","Igel","Spaghetti","Hamburger","Sandwich",
"Ei","Huhn","Kuh","Schaf","Schwein","Pferd","Affe","Panda","Koala","Krokodil",
"Flamingo","Oktopus","Krabbe","Qualle","Seepferdchen","Delfin","Anker",
"Segelboot","U-Boot","Hubschrauber","Heißluftballon","Traktor",
"Feuerwehrauto","Krankenwagen","Motorrad","Skateboard","Roller","Schlitten",
"Ski","Fußball","Basketball","Tennis","Kegeln","Dartscheibe","Schach",
"Würfel","Puzzle","Kreisel","Marionette","Nest","Feder","Flügel","Kralle",
"Fußabdruck","Knochen","Gehirn","Herz","Zahn","Schnurrbart","Bart","Zopf",
"Decke","Kissen","Bett","Sofa","Hocker","Lampe","Kamin","Staubsauger","Besen",
"Eimer","Gießkanne","Schubkarre","Schaufel","Rechen","Kaktus","Palme",
"Sonnenblume","Kirsche","Zitrone","Wassermelone","Ananas","Trauben","Mais",
"Brokkoli","Zwiebel","Chili","Lutscher","Donut","Popcorn","Pommes","Hotdog",
"Taco","Sushi","Teekanne","Tasse","Strohhalm","Flasche","Fass","Korb",
"Koffer","Rucksack","Geldbörse","Münze","Sparschwein","Diamant","Ring","Lupe",
"Fernglas","Teleskop","Kamera","Briefumschlag","Briefmarke","Zeitung",
"Kalender","Gemälde","Pinsel","Statue","Brunnen","Pyramide","Sphinx","Höhle",
"Wasserfall","Wüste","Wald","Sumpf","Eisberg","Komet","Satellit","Ufo",
"Sanduhr","Toaster","Mikrowelle","Kühlschrank","Waschmaschine","Wasserkocher",
"Mixer","Mülleimer","Kleiderbügel","Regal","Schublade","Vorhang","Teppich",
"Vase","Bilderrahmen","Lichtschalter","Steckdose","Glühbirne","Batterie",
"Tastatur","Computermaus","Bildschirm","Kopfhörer","Spielkonsole",
"Controller","Drohne","Drucker","USB-Stick","Radiergummi","Lineal",
"Büroklammer","Tacker","Reißzwecke","Schulranzen","Federmäppchen","Filzstift",
"Kreide","Tafel","Globus","Mikroskop","Reagenzglas","Stethoskop","Spritze",
"Pflaster","Krücke","Rollstuhl","Thermometer","Gürtel","Krawatte","Fliege",
"Hosenträger","Weste","Kimono","Schürze","Latzhose","Flipflops",
"Stöckelschuhe","Papagei","Pfau","Strauß","Fledermaus","Maulwurf","Biber",
"Eichhörnchen","Waschbär","Dachs","Frettchen","Hummer","Auster","Miesmuschel",
"Sardine","Forelle","Aal","Rochen","Schwertfisch","Piranha","Clownfisch",
"Polizist","Dieb","Arzt","Krankenschwester","Pilot","Soldat","Ninja",
"Wikinger","Riese","Oger","Elfe","Troll","Nadel","Faden","Knopf",
"Reißverschluss","Waage","Ventilator","Heizung","Türklingel","Briefkasten",
"Zaun","Fußmatte","Ziegelstein","Kran","Bagger","Helm","Boje","Badeanzug",
"Handtuch","Sonnenschirm","Kajak","Lokomotive","Waggon","Straßenbahn",
"Dschungel","Hügel","Klippe","Düne","Feld","Scheune","Gemüsegarten","Zoo",
"Museum","Bibliothek","Krankenhaus","Gefängnis","Supermarkt","Bäckerei",
"Restaurant","Stadion","Bahnhof","Flughafen","Hafen","Fabrik","Kirche",
"Wolkenkratzer","Gewitter","Raumschiff","Asteroid","Windrad","Rasenmäher",
"Bohrmaschine","Spülmaschine","Föhn","Bügeleisen","Himbeere","Blaubeere",
"Aprikose","Pflaume","Mango","Kokosnuss","Aubergine","Zucchini","Gurke",
"Lauch","Radieschen","Kohl","Blumenkohl","Erbsen","Bohne","Spinat","Waffel",
"Torte","Omelett","Wurst","Schinken","Senf","Ketchup","Limonade","Joghurt",
"U-Bahn","Mayonnaise",
],
"3": [
"Wasserspeier","Kirchenfenster","Labyrinth","Schachbrett","Domino","Xylophon",
"Akkordeon","Harfe","Geige","Saxophon","Taucheranzug","Fallschirm",
"Seilrutsche","Seiltänzer","Trampolin","Periskop","Zeppelin","Seilbahn",
"Robbe","Chamäleon","Faultier","Schnabeltier","Gürteltier","Narwal","Axolotl",
"Gottesanbeterin","Käfer","Glühwürmchen","Rabe","Katapult","Rüstung","Schild",
"Armbrust","Laterne","Kronleuchter","Harpune","Hängematte","Baumhaus",
"Aquarium","Vogelscheuche","Umzug","Stau","Schlafwandler","Imker",
"Schornsteinfeger","Bauchredner","Schlangenmensch","Dompteur","Archäologe",
"Dirigent","Sandburg","Kissenschlacht","Schneckenrennen","Achterbahn",
"Flohmarkt","Schatzsuche","Feuerwerk","Sonnenfinsternis","Polarlicht","Ebbe",
"Treibsand","Lawine","Erdbeben","Tornado","Hitzewelle","Nebel","Tau",
"Tropfstein","Geysir","Fingerabdruck","Geheimcode","Geheimgang","Tresor",
"Ausgrabung","Mumifizierung","Winterschlaf","Vogelzug","Tarnung","Häutung",
"Picknick","Grillabend","Fondue","Frühstücksei","Hochzeitstorte","Kater",
"steifer Nacken","Muskelkater","Gänsehaut","Mittagsschlaf","Niesen",
"Turmspringen","Jonglieren","Klettern","Reiten","Fechten","Bogenschießen",
"Tauchen","Surfen","Kanu","Gleitschirm","Mechaniker","Klempner","Elektriker",
"Briefträger","Gärtner","Bäcker","Friseur","Zahnarzt","Tierarzt",
"Feuerwehrmann","Jongleur","Akrobat","Pantomime","Koch","Kellner",
"Schiedsrichter","Detektiv","Spion","Cowboy","Gladiator","Verkleidung",
"Karneval","Parade","Konzert","Karaoke","Hochzeit","Verstecken","Blinde Kuh",
"Reise nach Jerusalem","Seilspringen","Himmel und Hölle","Murmeln",
"Wasserpark","Paintball","Tauziehen","Armdrücken","Bungeejumping","Marathon",
"Hochsprung","Stabhochsprung","Speerwurf","Turnen","Wasserball","Curling",
"Tischtennis","Badminton","Boule","Vollmond","Sternschnuppe","Sternbild",
"Milchstraße","Schwarzes Loch","Umlaufbahn","Mondlandung","Raketenstart",
"Landung","Schiffbruch","Riesenrad","Wasserrad","Bauer","Chirurg","Richter",
"Anwalt","Kapitän","Holzfäller","Schmied","Schäfer","Bergmann","Stuntman",
"Bildhauer","Fotograf","Bergsteigen","Wandern","Schneeballschlacht",
"Zugbrücke","Kerker","Festung","Presslufthammer","Baugerüst","Kettensäge",
"Fernrohr","Wetterfahne","Blitzableiter","Steuerrad","Bullauge","Floß","Tipi",
"Hütte","Oase","Savanne","Schlucht","Krater","Seelöwe","Walross","Luchs",
"Gepard","Panther","Hyäne","Gazelle","Wisent","Elch","Kolibri","Pelikan",
"Reiher","Storch","Leguan","Kobra","Skorpion","Hagel","Überschwemmung",
"Orkan","Tukan",
],
"4": [
"Nostalgie","Eifersucht","Schlaflosigkeit","Schwindel","Schluckauf","Schauer",
"Telepathie","Hypnose","Amnesie","Déjà-vu","Platzangst","Aufschieberitis",
"Metamorphose","Photosynthese","Schwerelosigkeit","Schwerkraft","Echo",
"Stille","Chaos","Unendlichkeit","Freiheit","Demokratie","Philosophie",
"Bewusstsein","Intuition","Sarkasmus","Ironie","Missverständnis","Gerücht",
"Aberglaube","Albtraum","Einsamkeit","Mut","Geduld","Hoffnung","Schicksal",
"Zufall","Gleichgewicht","Geschwindigkeit","Zeit","Elektrizität","WLAN",
"Allergie","Karma","Paradox","Fata Morgana","Evolution","Harmonie","Neugier",
"Schüchternheit","Melancholie","Euphorie","Adrenalin","Empathie","Charisma",
"Aura","Dilemma","Utopie","Anarchie","Propaganda","Zensur","Inflation",
"Arbeitslosigkeit","Burnout","Routine","Monotonie","Spontaneität",
"Bescheidenheit","Stolz","Verrat","Vergebung","Spannung","Instinkt","Ego",
"Stimmung","Dankbarkeit","Scham","Schuld","Reue","Zweifel","Vertrauen",
"Misstrauen","Angst","Gelassenheit","Pech","Illusion","Fantasie",
"Kreativität","Inspiration","Motivation","Müdigkeit","Langeweile","Stress",
"Panik","Phobie","Besessenheit","Nervosität","Humor","Höflichkeit","Respekt",
"Gerechtigkeit","Ungerechtigkeit","Gleichheit","Brüderlichkeit","Toleranz",
"Weisheit","Wahnsinn","Tagtraum","Seufzer","Angeber","Peinlichkeit","Rache",
"Klatsch","Fernweh","Ohrwurm","Erinnerung","Traum","Wahrheit","Lüge",
"Geheimnis","Versprechen","Witz","Rätsel","Sieg","Niederlage","Großzügigkeit",
"Freundlichkeit","Faulheit","Wut","Freude","Traurigkeit","Furcht","Liebe",
"Freundschaft","Kindheit","Jugend","Ewigkeit","Dämmerung","Morgengrauen",
"Notfall","Verspätung","Streik","Glück","Kummer","Überraschung","Appetit",
"Hunger","Durst","Fieber","Migräne","Urlaub","Heimweh",
],
},

"it": {
"1": [
"gatto","cane","casa","sole","luna","stella","albero","fiore","macchina",
"bicicletta","aereo","barca","treno","razzo","montagna","spiaggia","pizza",
"gelato","pane","formaggio","torta","mela","banana","fragola","carota",
"fungo","pesce","squalo","balena","farfalla","ragno","serpente","elefante",
"giraffa","leone","pinguino","tartaruga","coniglio","topo","drago","fantasma",
"pirata","robot","strega","unicorno","sirena","cavaliere","castello","corona",
"chitarra","pianoforte","tamburo","tromba","microfono","televisione",
"telefono","computer","orologio","ombrello","occhiali","cappello","scarpa",
"calzino","pantaloni","sciarpa","palloncino","aquilone","scivolo","altalena",
"piscina","doccia","spazzolino","sapone","specchio","finestra","porta",
"scala","ponte","faro","mulino","iglù","tenda","falò","arcobaleno","nuvola",
"fulmine","neve","pupazzo di neve","regalo","compleanno","pagliaccio","circo",
"mago","vampiro","scheletro","zombi","mummia","alieno","astronauta","pianeta",
"mano","piede","naso","bocca","orecchio","braccio","gamba","dito","testa",
"lingua","panca","tavolo","sedia","ciotola","piatto","forchetta","coltello",
"cucchiaio","bicchiere","padella","latte","succo","caffè","tè","miele",
"cubetto di ghiaccio","caramella","cioccolato","biscotto","autobus","taxi",
"ruota","chiodo","vite","sega","ascia","corda","scatola","borsa","berretto",
"guanto","stivale","vestito","gonna","cappotto","pigiama","orso","lupo",
"volpe","tigre","zebra","anatra","pulcino","nodo","neonato","re","regina",
"principe","principessa","angelo","pioggia","mare","lago","fiume","scuola",
"giardino","erba","foglia","arancia","pera","pesca","kiwi","melone","zucca",
"pomodoro","burro","marmellata","zuppa","riso","occhio","ginocchio","gomito",
"gallo","capra","asino","formica","mosca","coccinella","cigno","piccione",
"aquila","ippopotamo","rinoceronte","gorilla","cammello","cervo","cinghiale",
],
"2": [
"vulcano","isola","tesoro","chiave","lucchetto","candela","libro","matita",
"forbici","martello","cacciavite","calamita","bussola","mappa","bandiera",
"trofeo","medaglia","dinosauro","canguro","gufo","ape","lumaca","rana",
"riccio","spaghetti","hamburger","panino","uovo","gallina","mucca","pecora",
"maiale","cavallo","scimmia","panda","koala","coccodrillo","fenicottero",
"polpo","granchio","medusa","cavalluccio marino","delfino","ancora",
"barca a vela","sottomarino","elicottero","mongolfiera","trattore",
"camion dei pompieri","ambulanza","motocicletta","skateboard","monopattino",
"slitta","sci","calcio","pallacanestro","tennis","bowling","freccette",
"scacchi","dado","puzzle","trottola","marionetta","nido","piuma","ala",
"artiglio","impronta","osso","cervello","cuore","dente","baffi","barba",
"treccia","coperta","cuscino","letto","divano","sgabello","lampada","camino",
"aspirapolvere","scopa","secchio","annaffiatoio","carriola","pala",
"rastrello","cactus","palma","girasole","ciliegia","limone","anguria",
"ananas","uva","mais","broccoli","cipolla","peperoncino","lecca-lecca",
"ciambella","popcorn","patatine fritte","hot dog","sushi","teiera","tazza",
"cannuccia","bottiglia","botte","cesto","valigia","zaino","portafoglio",
"moneta","salvadanaio","diamante","anello","lente d'ingrandimento","binocolo",
"telescopio","macchina fotografica","busta","francobollo","giornale",
"calendario","quadro","pennello","statua","fontana","piramide","sfinge",
"grotta","cascata","deserto","foresta","palude","iceberg","cometa",
"satellite","ufo","galassia","clessidra","tostapane","frigorifero",
"microonde","lavatrice","bollitore","frullatore","cestino","gruccia",
"scaffale","cassetto","tappeto","vaso","cornice","interruttore",
"presa elettrica","lampadina","batteria","tastiera","mouse","schermo",
"cuffie","console","joystick","drone","stampante","chiavetta USB","gomma",
"righello","graffetta","cucitrice","puntina","astuccio","pennarello","gesso",
"lavagna","mappamondo","microscopio","provetta","stetoscopio","siringa",
"cerotto","stampella","sedia a rotelle","termometro","cintura","cravatta",
"papillon","bretelle","gilet","kimono","grembiule","salopette","infradito",
"tacchi alti","pappagallo","pavone","struzzo","pipistrello","talpa","castoro",
"scoiattolo","procione","tasso","furetto","aragosta","ostrica","cozza",
"sardina","trota","anguilla","razza","pesce spada","piranha",
"pesce pagliaccio","poliziotto","ladro","medico","infermiera","pilota",
"soldato","ninja","vichingo","gigante","orco","elfo","troll","ago","filo",
"bottone","cerniera","bilancia","ventilatore","termosifone","campanello",
"cassetta postale","recinto","zerbino","mattone","gru","escavatore","casco",
"boa","costume da bagno","asciugamano","ombrellone","cerchio","kayak",
"locomotiva","vagone","tram","metropolitana","giungla","collina","scogliera",
"duna","campo","fienile","orto","zoo","museo","biblioteca","ospedale",
"prigione","banca","supermercato","panetteria","ristorante","stadio",
"stazione","aeroporto","porto","fabbrica","chiesa","grattacielo","temporale",
"navetta spaziale","asteroide","tosaerba","trapano","lavastoviglie",
"asciugacapelli","ferro da stiro","lampone","mirtillo","albicocca","prugna",
"mango","noce di cocco","melanzana","zucchina","cetriolo","porro","ravanello",
"cavolo","cavolfiore","piselli","fagiolo","spinaci","crostata","frittata",
"salsiccia","prosciutto","senape","ketchup","maionese","limonata","yogurt",
],
"3": [
"gargolla","vetrata","labirinto","scacchiera","domino","xilofono",
"fisarmonica","arpa","violino","sassofono","scafandro","paracadute",
"teleferica","funambolo","trampolino","periscopio","dirigibile","foca",
"camaleonte","bradipo","ornitorinco","armadillo","narvalo","axolotl",
"mantide religiosa","scarabeo","lucciola","corvo","catapulta","armatura",
"scudo","balestra","lanterna","candelabro","arpione","amaca",
"casa sull'albero","acquario","spaventapasseri","riccio di mare","trasloco",
"ingorgo","sonnambulo","apicoltore","spazzacamino","ventriloquo",
"contorsionista","domatore","archeologo","direttore d'orchestra",
"castello di sabbia","battaglia di cuscini","corsa delle lumache",
"montagne russe","mercatino delle pulci","caccia al tesoro",
"fuochi d'artificio","eclissi solare","aurora boreale","bassa marea",
"sabbie mobili","valanga","terremoto","tornado","ondata di caldo","nebbia",
"rugiada","stalattite","geyser","impronte digitali","codice segreto",
"passaggio segreto","cassaforte","scavo archeologico","mummificazione",
"letargo","migrazione","mimetismo","muta","picnic","grigliata","fonduta",
"uovo alla coque","torta nuziale","postumi della sbornia","torcicollo",
"crampo","pelle d'oca","pisolino","starnuto","tuffo","giocoleria",
"arrampicata","equitazione","scherma","tiro con l'arco","immersione","surf",
"canoa","parapendio","meccanico","idraulico","elettricista","postino",
"giardiniere","panettiere","parrucchiere","dentista","veterinario","pompiere",
"giocoliere","acrobata","mimo","cuoco","cameriere","arbitro","detective",
"spia","cowboy","gladiatore","travestimento","carnevale","sfilata","concerto",
"karaoke","matrimonio","nascondino","mosca cieca","sedie musicali",
"salto della corda","campana","biglie","parco acquatico","paintball",
"tiro alla fune","braccio di ferro","bungee jumping","maratona",
"salto in alto","salto con l'asta","lancio del giavellotto","ginnastica",
"pallanuoto","curling","ping pong","badminton","bocce","luna piena",
"stella cadente","costellazione","via lattea","buco nero","orbita",
"allunaggio","decollo","atterraggio","naufragio","ruota panoramica",
"mulino ad acqua","contadino","chirurgo","giudice","avvocato","capitano",
"boscaiolo","fabbro","pastore","minatore","scultore","fotografo","alpinismo",
"escursionismo","battaglia di palle di neve","ponte levatoio","fortezza",
"martello pneumatico","impalcatura","motosega","cannocchiale","banderuola",
"parafulmine","timone","oblò","zattera","capanna","oasi","savana","cratere",
"leone marino","tricheco","lince","ghepardo","pantera","iena","gazzella",
"bisonte","alce","colibrì","tucano","pellicano","airone","cicogna","iguana",
"cobra","scorpione","grandine","alluvione","uragano",
],
"4": [
"nostalgia","gelosia","insonnia","vertigine","singhiozzo","brivido",
"telepatia","ipnosi","amnesia","déjà vu","claustrofobia","procrastinazione",
"metamorfosi","fotosintesi","assenza di gravità","gravità","eco","silenzio",
"caos","infinito","libertà","democrazia","filosofia","coscienza","intuizione",
"sarcasmo","ironia","malinteso","pettegolezzo","superstizione","incubo",
"solitudine","coraggio","pazienza","speranza","destino","fortuna",
"equilibrio","velocità","tempo","elettricità","wifi","allergia","karma",
"paradosso","miraggio","evoluzione","armonia","curiosità","timidezza",
"malinconia","euforia","adrenalina","empatia","carisma","aura","dilemma",
"utopia","anarchia","propaganda","censura","inflazione","disoccupazione",
"esaurimento","routine","monotonia","spontaneità","modestia","orgoglio",
"tradimento","perdono","suspense","istinto","ego","atmosfera","gratitudine",
"vergogna","colpa","rimpianto","dubbio","fiducia","diffidenza","ansia",
"serenità","sfortuna","coincidenza","illusione","immaginazione","creatività",
"ispirazione","motivazione","stanchezza","noia","stress","panico","fobia",
"ossessione","nervosismo","umorismo","cortesia","rispetto","giustizia",
"ingiustizia","uguaglianza","fratellanza","tolleranza","saggezza","follia",
"sogno ad occhi aperti","sospiro","sbruffone","imbarazzo","vendetta",
"nostalgia di casa","memoria","sogno","verità","bugia","segreto","promessa",
"scherzo","indovinello","enigma","mistero","vittoria","sconfitta",
"generosità","gentilezza","pigrizia","rabbia","gioia","tristezza","paura",
"amore","amicizia","infanzia","giovinezza","vecchiaia","eternità","tramonto",
"alba","emergenza","ritardo","sciopero","inquinamento","felicità","sorpresa",
"appetito","fame","sete","febbre","emicrania","vacanze",
],
},

}

LANG_NAMES = {"fr": "🇫🇷 Français", "en": "🇬🇧 English", "es": "🇪🇸 Español",
              "de": "🇩🇪 Deutsch", "it": "🇮🇹 Italiano"}
